#!/bin/bash

set -euo pipefail

remote_name="$1"

while read local_ref local_sha remote_ref remote_sha; do
    if [ "$remote_name" = "origin" ] && [ "$remote_ref" = "refs/heads/main" ]; then
        just check-all
        break
    fi
done
