class Blob:
    def upload_from_string(
        self,
        data: bytes | str,
        content_type: str = "text/plain",
        if_generation_match: int | None = None,
    ) -> None: ...
    @property
    def metadata(self) -> dict[str, str] | None: ...
    @metadata.setter
    def metadata(self, value: dict[str, str] | None) -> None: ...
    @property
    def content_encoding(self) -> str: ...
    @content_encoding.setter
    def content_encoding(self, value: str) -> None: ...
