from google.cloud.storage import Blob, Client

class Bucket:
    def __init__(self, client: Client, name: str | None = None) -> None: ...
    def blob(self, blob_name: str) -> Blob: ...
    def get_blob(self, blob_name: str) -> Blob | None: ...
