name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - working-directory: .
            files: "*.py lib/*.py"
          - working-directory: new-games-to-db
            files: "*.py"
          - working-directory: store-in-gcs
            files: "*.py"
    defaults:
      run:
        working-directory: ${{ matrix.working-directory }}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uv run ruff check -q --output-format=github ${{ matrix.files }}
      - run: uv run ruff format --diff ${{ matrix.files }}
      - run: uv run basedpyright ${{ matrix.files }}
  check:
    name: CI passed
    if: always()
    permissions: {}
    needs:
      - ci
    runs-on: ubuntu-latest
    steps:
      - name: Check that all matrix elements in all jobs passed
        uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe  # v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
